<?php

namespace DeptOfScrapyardRobotics\Sensors\TSL2591\TSL2591\Enums;

enum TSL2591WriteRegister: int
{
    case ENABLE_REGISTER = 0x00;
    case CONTROL_REGISTER = 0x01;
    case THRESHOLD_LOW_LOW_REGISTER = 0x04;
    case THRESHOLD_LOW_HIGH_REGISTER = 0x05;
    case THRESHOLD_HIGH_LOW_REGISTER = 0x06;
    case THRESHOLD_HIGH_HIGH_REGISTER = 0x07;
    case NO_PERSIST_THRESHOLD_LOW_LOW_REGISTER = 0x08;
    case NO_PERSIST_THRESHOLD_LOW_HIGH_REGISTER = 0x09;
    case NO_PERSIST_THRESHOLD_HIGH_LOW_REGISTER = 0x0A;
    case NO_PERSIST_THRESHOLD_HIGH_HIGH_REGISTER = 0x0B;
    case PERSIST_FILTER_REGISTER = 0x0C;
}
